###############################################################################
# 本项目的源代码在MPL2.0协议下发布，同时附加以下条目：                            #
# 非商业性使用 — 不得将此项目及其衍生的项目的源代码和二进制产品用于任何商业和盈利用途#
###############################################################################
Version: by小宋
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
debug: false
# 消息推送配置，method 0 为禁用 1 为webApi模式 2 为本地smtp模式 3 为qmsg模式(qq号模式)
# 消息推送配置，method 4 为qmsg模式(qq群模式) method 5 为企业微信模式 method 6 为Server酱模式
notifyOption:
    method: 2
    #############配置1-4选填一个即可
    #############1 webApi配置,根据不同api可能需要自行修改推送模块
    mailApiUrl: 'http://api.ruoli.cc/mail/sendMail'
    #############2 发信方邮箱账号密码,smtp服务器qq邮箱为smtp.qq.com,163邮箱为smtp.163.com
    smtpOption:
        userName: '776109754@qq.com'
        passWord: 'xkldhsbrzkolbebb'
        server: 'smtp.qq.com'
    #############3 完善qmsgKey即可,需要完善-user字段中qId参数，详见下方例子
    qmsgOption:
        key: ''
        baseUrl: 'https://qmsg.zendee.cn/'
    #############4 企业微信配置
    qywxOption:
        corpid: ''
        corpsecret: ''
        agentid: ''
    #############5 Server酱的Key请在下方rcvAcc处填写
    serverChanOption:
        baseUrl: 'https://sctapi.ftqq.com/'
# 默认不填，如需使用先开通腾讯云OCR服务，再申请API密钥
ocrOption:
    SecretId: 'APIid'
    SecretKey: 'APIkey'
# 如IP被拦截，可设置全局HTTP代理
httpProxy: ''
#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
    # 以下配置为信息收集
#    - user:
#        # 任务类型（收集：0、签到：1、查寝：2、政工签到：3、教师工作日志：4）
#        type: 0
#        # school 学校全称
#        schoolName: '南京晓庄学院'
#        # username 学号或者工号
#        username: '19130111'
#        # password 密码
#        password: 'songjh0918'
#        # 地址信息
#        address: '江苏省苏州市昆山市漓江路53号'
#        notifyOption:
#            # method和顶部参数一致，不填默认按照顶部参数执行
#            # method: 0
#            # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
#            rcvAcc: '776109754@qq.com'
#        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#        # lon 经度
#        lon: 121.063054
#        # lat 纬度
#        lat: 31.407163
#        # 是否检查表单的标题（1代表检查，0代表不检查）
#        checkTitle: 1
#        # 表单信息
#        forms:
#            - form:
#                title: 你今天的体温状况？
#                value: 正常（37.3℃以下）
##            - form:
##                title: 你今天是否在校？
##                value: 不在校
#            - form:
#                title: 今天健康码颜色（以当地健康码为准）？
#                value: 绿码
#            - form:
#                title: 今天你是否位于中高风险地区？
#                value: 否
#            - form:
#                title: 今天你及共同居住人是否有发热、咳嗽、胸闷、腹泻等症状？
#                value: 否
##            - form:
##                title: 今天你及共同居住人出现体温异常，且有咳嗽、胸闷、腹泻等症状，请填写具体情况
##                value: Null
#            - form:
#                title: 今天你及共同居住人是否有隔离情况？
#                value: 无隔离
##            - form:
##                title: 今天如有隔离情况（居家隔离、集中隔离）请填写具体情况和隔离地点
##                value: Null

#    - user:
#        # 任务类型（收集：0、签到：1、查寝：2、政工签到：3、教师工作日志：4）
#        type: 0
#        # school 学校全称
#        schoolName: '南京晓庄学院'
#        # username 学号或者工号
#        username: '19130111'
#        # password 密码
#        password: 'songjh0918'
#        # 地址信息
#        address: '江苏省南京市江宁区吉祥路3601号'
#        notifyOption:
#            # method和顶部参数一致，不填默认按照顶部参数执行
#            # method: 0
#            # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
#            rcvAcc: '776109754@qq.com'
#        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#        # lon 经度
#        lon: 118.910263
#        # lat 纬度
#        lat: 31.899953
#        # 是否检查表单的标题（1代表检查，0代表不检查）
#        checkTitle: 1
#        # 表单信息
#        forms:
#            - form:
#                title: 你今天的体温状况？
#                value: 正常（37.3℃以下）
#            # - form:
#            #     title: 你今天是否在校？
#            #     value: 不在校
#            - form:
#                title: 今天健康码颜色（以当地健康码为准）？
#                value: 绿码
#            - form:
#                title: 今天你是否位于中高风险地区？
#                value: 否
#            - form:
#                title: 今天你及共同居住人是否有发热、咳嗽、胸闷、腹泻等症状？
#                value: 否
##            - form:
##                title: 今天你及共同居住人出现体温异常，且有咳嗽、胸闷、腹泻等症状，请填写具体情况
##                value: Null
#            - form:
#                title: 今天你及共同居住人是否有隔离情况？
#                value: 无隔离
##            - form:
##                title: 今天如有隔离情况（居家隔离、集中隔离）请填写具体情况和隔离地点
##                value: Null

#     以下配置为签到
    - user:
        # 任务类型（收集：0、签到：1、查寝：2）
        type: 1
        # school 学校全称
        schoolName: '南京晓庄学院'
        # username 学号或者工号
        username: '19130111'
        # password 密码
        password: 'songjh0918'
        # address 地址，定位信息
        address: '江苏省南京市江宁区吉祥路3601号'
        notifyOption:
            # method和顶部参数一致，不填默认按照顶部参数执行
            # method: 0
            # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
            rcvAcc: '776109754@qq.com'
        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
        # lon 经度
        lon: 118.910108
        # lat 纬度
        lat: 31.89995
        # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
        abnormalReason: ''
        # photo 签到照片，不需要可不填，或者直接删除
        photo:
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        # 表单信息
        forms:
            - form:
                title: 你今天的体温状况？
                value: 正常（37.3℃以下）
            - form:
                title: 今天健康码颜色（以当地健康码为准）？
                value: 绿码
            - form:
                title: 今天你及共同居住人是否有发热、咳嗽、胸闷、腹泻等症状？
                value: 否
            - form:
                title: 今天你及共同居住人是否有隔离情况？
                value: 无隔离
#    - user:
#        # 任务类型（收集：0、签到：1、查寝：2）
#        type: 1
#        # school 学校全称
#        schoolName: '南京晓庄学院'
#        # username 学号或者工号
#        username: '19130114'
#        # password 密码
#        password: 'xjc951357'
#        # address 地址，定位信息
#        address: '江苏省南京市江宁区吉祥路3601号'
#        notifyOption:
#            # method和顶部参数一致，不填默认按照顶部参数执行
#            # method: 0
#            # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
#            rcvAcc: '2684033506@qq.com'
#        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#        # lon 经度
#        lon: 118.910108
#        # lat 纬度
#        lat: 31.89995
#        # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
#        abnormalReason: ''
#        # photo 签到照片，不需要可不填，或者直接删除
#        photo:
#        # 是否检查表单的标题（1代表检查，0代表不检查）
#        checkTitle: 1
#        # 表单信息
#        forms:
#            - form:
#                title: 你今天的体温状况？
#                value: 正常（37.3℃以下）
#            - form:
#                title: 今天健康码颜色（以当地健康码为准）？
#                value: 绿码
#            - form:
#                title: 今天你及共同居住人是否有发热、咳嗽、胸闷、腹泻等症状？
#                value: 否
#            - form:
#                title: 今天你及共同居住人是否有隔离情况？
#                value: 无隔离

    # 第四个用户配置
    # 以下配置为查寝
#    - user:
#        # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
#        type: 2
#        # school 学校全称
#        schoolName: '南京晓庄学院'
#        # username 学号或者工号
#        username: '19130111'
#        # password 密码
#        password: 'songjh0918'
#        # 地址信息
#        address: '江苏省南京市江宁区吉祥路3601号'
#        notifyOption:
#            # method和顶部参数一致，不填默认按照顶部参数执行
#            # method: 0
#            # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
#            rcvAcc: '776109754@qq.com'
#        # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
#        # lon 经度
#        lon: 118.910263
#        # lat 纬度
#        lat: 31.899953
#        # abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
#        abnormalReason: ''
#        # photo 签到照片，不需要可不填，或者直接删除
#        photo: sign.jpg